steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'hello-gonews'
  - '--gen2'
  - '--runtime=python312'
  - '--region=europe-west1'
  - '--source=.'
  - '--entry-point=run_gonews' # Test ettiğimiz ana fonksiyonumuz
  - '--trigger-http'
  - '--allow-unauthenticated'
  - '--memory=1GiB'           # YENİ SATIR: Belleği 1 GB'a çıkardık
  - '--timeout=300s'          # YENİ SATIR: Zaman aşımını 5 dakikaya çıkardık
options:
  logging: CLOUD_LOGGING_ONLY